#
# Copyright 2015, Noah Kantrowitz
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'spec_helper'

describe PoiseService::Providers::Upstart do
  service_provider('upstart')
  step_into(:poise_service)
  recipe do
    poise_service 'test' do
      command 'myapp --serve'
    end
  end

  it { is_expected.to render_file('/etc/init/test.conf').with_content(<<-EOH) }
# test generated by poise-service

description "test"

start on runlevel [2345]
stop on runlevel [!2345]

respawn
respawn limit 10 5
umask 022
chdir /
setuid root
kill signal TERM

exec myapp --serve
EOH

  context 'with action :disable' do
    recipe do
      poise_service 'test' do
        action :disable
      end
    end

    it { is_expected.to delete_file('/etc/init/test.conf') }
  end # /context with action :disable
end
